FROM golang:1.19-alpine

RUN apk add --no-cache redis

COPY /docker/dev/redis.conf /usr/local/etc/redis/redis.conf

WORKDIR /
COPY ../../go.mod ../../go.sum ../../main_test.go ../../main.go /  
COPY ../../public/ /public

EXPOSE 4444 4000 6379

RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest
RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o main .

