apiVersion: apps/v1
kind: Deployment
metadata:
  name: goredis-deployment
  labels:
    app: redis
    namespace: {{ .Values.namespaces.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.redis.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        args: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        volumeMounts:
        - name: redis-storage
          mountPath: "/var/lib/redis" 
        imagePullPolicy: Never  
      restartPolicy: Always
      
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc


