apiVersion: v1
kind: Service
metadata:
  name: goapp-service
  namespace: {{ .Values.namespaces.name }}
spec:
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: {{ .Values.goapp.externalport }}
      targetPort: {{ .Values.goapp.port }}