apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  labels:
    app: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: goapp:latest
        args: ["/main"]
        ports:
          - containerPort: 4444
            protocol: TCP
        envFrom:
        - configMapRef:
            name: goapp-config
        volumeMounts:
        - name: secret-volume
          mountPath: "/app/secrets"
          readOnly: true
        imagePullPolicy: Never  
      restartPolicy: Always

      volumes:
      - name: secret-volume
        secret:
          secretName: goapp-secrets



