name: goapp pipeline

on:
  push:
    branches:
      - main

jobs:
  
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      # Build and test go app   
      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v .
      
      # Build and push to the registry the prod images 
      # - name: Generate UUID GoApp
      #   id: UUID_goapp
      #   run: echo "IMAGE_NAME_APP=$(uuidgen)" >> $GITHUB_ENV

      # - name: Generate UUID Redis
      #   id: UUID_redis
      #   run: echo "IMAGE_NAME_REDIS=$(uuidgen)" >> $GITHUB_ENV

      # - name: Build GoApp Docker image
      #   run: docker build -f docker/prod/Dockerfile.go.prod -t ttl.sh/${IMAGE_NAME_APP}:10m .
      
      # - name: Build Redis Docker image       
      #   run: docker build -f docker/prod/Dockerfile.redis.prod  -t ttl.sh/${IMAGE_NAME_REDIS}:10m .

      # - name: Push GoApp Docker image to the ttl registry
      #   run: docker push ttl.sh/${IMAGE_NAME_APP}:10m
      
      # - name: Push Redis Docker image to the ttl registry
      #   run: docker push ttl.sh/${IMAGE_NAME_REDIS}:10m
      
      # Deploy to prod
      - name: build example and deploy to minikube
        uses: actions/checkout@v4
        with:
          repository: Zernez/UNIwise

      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      
      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Build images
        run: |
          minikube image build -f docker/prod/Dockerfile.go.prod . -t goappprod:latest
          minikube image build -f docker/prod/Dockerfile.redis.prod . -t goredisprod:latest 

      - name: Deploy to minikube
        run:
          kubectl apply -f k8s/prod 

      - name: Test service URLs
        run: |
          minikube service list
          echo "------------------curl the service------------------"
          curl $(http://localhost:30000)