name: goapp pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      # Build and test go app   
      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v .
      
      # Build and push to the registry the prod images 
      - name: Generate UUID GoApp
        id: UUID_goapp
        run: echo "IMAGE_NAME_APP=$(uuidgen)" >> $GITHUB_ENV

      - name: Generate UUID Redis
        id: UUID_redis
        run: echo "IMAGE_NAME_REDIS=$(uuidgen)" >> $GITHUB_ENV

      - name: Build GoApp Docker image
        run: docker build -f docker/prod/Dockerfile.go.prod -t ttl.sh/${IMAGE_NAME_APP}:10m .
      
      - name: Build Redis Docker image       
        run: docker build -f docker/prod/Dockerfile.redis.prod  -t ttl.sh/${IMAGE_NAME_REDIS}:10m .

      - name: Push GoApp Docker image to the ttl registry
        run: docker push ttl.sh/${IMAGE_NAME_APP}:10m
      
      - name: Push GoApp Docker image to the ttl registry
        run: docker push ttl.sh/${IMAGE_NAME_REDIS}:10m
      
      # Deploy to prod
      - name: Deploy
        run: |-
          kubectl apply -f k8s/prod