name: goapp pipeline

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Run tests
      # -v to provide detailed logging ./... run tests from current and all subdirectories 
        run: go test -v ./...
      
      # Use github env to pass variable
      - name: Generate Image Name
        id: image_name
        run: echo "IMAGE_NAME=$(uuidgen)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ttl.sh/${IMAGE_NAME}:1h .

      - name: Push the image to ttl.sh
        run: docker push ttl.sh/${IMAGE_NAME}:1h