name: goapp pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      # Build and test go app   

      - name: Build
        run: go build -v .

      - name: Run tests
        run: go test -v .
      
      # Build and push to the registry the images

      - name: Generate
        id: image_name
        run: echo "IMAGE_NAME=$(uuidgen)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ttl.sh/${IMAGE_NAME}:1h .

      - name: Push Docker image to the ttl registry
        run: docker push ttl.sh/${IMAGE_NAME}:1h
      
      # Deploy to prod

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        working-directory: ./k8s
        run: |-
          kubectl apply -f .